[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.17", features = ["csr"] }
leptos_router = { version = "0.8.13" }
leptos-use = { version = "0.18.3" }
console_error_panic_hook = "0.1.7"
codee = { version = "0.3.5", features = ["json_serde"] }

serde = { workspace = true }
uuid = { workspace = true }
time = { workspace = true }

thiserror = { workspace = true }

gloo-net = "0.7.0"
email_address = "0.2.9"
