version: '3'

vars:
  MIGRATIONS_PATH: "./migrations"

dotenv:
  - .env

tasks:
  migrate-up:
    desc: "Applies all pending migrations."
    summary: |
      Applies all pending migrations.
      
      Make sure MIGRATIONS_PATH and DATABASE_URL are set.

    cmd: migrate -path {{.MIGRATIONS_PATH}} -database "{{.DATABASE_URL}}" up
    requires:
      vars: [ MIGRATIONS_PATH, DATABASE_URL ]

  migrate-down:
    desc: "Reverts the last applied migration."
    summary: |
      Reverts the last applied migration.

      Make sure MIGRATIONS_PATH and DATABASE_URL are set.

    cmd: migrate -path {{.MIGRATIONS_PATH}} -database "{{.DATABASE_URL}}" down 1
    requires:
      vars: [ MIGRATIONS_PATH, DATABASE_URL ]

  migrate-down-all:
    desc: "Reverts all migrations."
    summary: |
      Reverts all applied migration.
      
      Make sure MIGRATIONS_PATH and DATABASE_URL are set.

    cmd: migrate -path {{.MIGRATIONS_PATH}} -database "{{.DATABASE_URL}}" down
    requires:
      vars: [ MIGRATIONS_PATH, DATABASE_URL ]

  migrate-create:
    desc: "Creates a new up/down migration file with specific name."
    summary: |
      Creates a new up/down migration file with specific name.
      
      Make sure MIGRATIONS_PATH and NAME are set.

    cmd: migrate create -ext sql -dir {{.MIGRATIONS_PATH}} -seq {{.NAME}}
    requires:
      vars: [ MIGRATIONS_PATH, NAME ]

  migrate-force:
    desc: "Forces the database version to a specific version."
    summary: |
      Forces the database version to a specific version.
      
      Make sure MIGRATIONS_PATH, DATABASE_URL  and VERSION are set.

    cmd: migrate -path {{.MIGRATIONS_PATH}} -database "{{.DATABASE_URL}}" force {{.VERSION}}
    requires:
      vars: [ MIGRATIONS_PATH, VERSION ]